package com.microsoft.partnercatalyst.fortis.spark.transforms.topic

import org.scalatest.FlatSpec
import org.scalatest.BeforeAndAfter

class LuceneKeyphraseExtractorSpec extends FlatSpec with BeforeAndAfter {

  it should "find Spanish phrases" in {
    val extractor = new LuceneKeyphraseExtractor("es", keywords)
    val result = extractor.extractKeyphrases("Victimas por todas partes pero un acuerdo civico y militar se ha logrado. Martín Santiago estuvo presente. También hubo un poco de participación campesina. Un camión terminó volcado esta noche en la vía Panamericana cerca a la bomba San Juan. El carro se movilizaba en dirección La Enea - Terminal de Transportes. \\xa0 En su interior llevaba material, el cual, por el suceso, terminó en la carretera. La pirueta del vehículo ocasionó que se derribara un poste de energía eléctrica que se encontraba en el sector. En el incidente no se presentaron lesionados.")
    assert(result.toList.sortBy(_.matchedPhrase) == Set(
      Keyphrase("víctimas", Set("Victimas"), 1),
      Keyphrase("civico-militar", Set("militar"), 1),
      Keyphrase("campesinos", Set("campesina"), 1),
      Keyphrase("participación de campesinos", Set("campesina"), 1),
      Keyphrase("martín santiago", Set("Santiago"), 1),
      Keyphrase("bomba", Set("bomba"), 1)
    ).toList.sortBy(_.matchedPhrase))
  }

  val keywords = Set(
    "martín santiago",
    "víctimas",
    "invernal",
    "desplazad",
    "comunes",
    "asesina",
    "violacion",
    "volcion",
    "antipersonal",
    "antipersona",
    "cobro de vacunas",
    "droga",
    "cilindro bomba",
    "participación de campesinos",
    "civico-militar",
    "occiso",
    "toque de queda",
    "uniformado",
    "venezolanos",
    "ministerio de justicia",
    "cooperación internacional",
    "terremoto",
    "acuerdo de paz",
    "el ministro de justicia",
    "extorsion",
    "fumigación de cultivos ilícitos",
    "acceso",
    "bloquear va",
    "huracán",
    "municion",
    "zonas rurales",
    "coca",
    "campo colombiano",
    "guerrill",
    "acción integral de minas antipersonales",
    "acción integral de minas antipersonales",
    "coordinador residente",
    "libre movilidad",
    "ataque",
    "amenaza",
    "inundación",
    "recluido",
    "mineral",
    "zona veredal",
    "derecho internacional humanitario",
    "erpac",
    "brigada",
    "medidas de prevención",
    "campesinos",
    "participación política",
    "derechos humanos",
    "restriccion al acceso",
    "batallon",
    "medidas de prevención y lucha contra la corrupción",
    "eln",
    "programas de desarrollo con enfoque territorial",
    "garantías de seguridad social",
    "intimida",
    "desmovilizado",
    "enfrentamiento",
    "disparar",
    "toma de rehenes",
    "crisis",
    "paramilitares",
    "minero",
    "economía familiar y solidaria",
    "cartel",
    "desastre",
    "judicialización de redes de narcotráfico",
    "judicialización de redes de narcotráfico",
    "agc",
    "gaula",
    "incautación",
    "captura",
    "muere",
    "jurisdiccón agraria",
    "defensores de derechos humanos",
    "perdidos",
    "afectados",
    "fuerzas armadas",
    "internacional",
    "autodefensas gaitanistas",
    "justicia y paz",
    "violad",
    "pérdidas",
    "desvinculacion",
    "retorno",
    "columna",
    "violar",
    "secretariado",
    "hostigamiento",
    "terror",
    "derechos de las víctimas",
    "financiamiento acuerdos de paz",
    "proteccion",
    "intimidados",
    "negociaciones de paz",
    "detener",
    "atemoriza",
    "desarrollo rural",
    "derechos de los campesinos colombianos",
    "derechos de los campesinos colombianos",
    "necesidades humanitarias",
    "rastrojos",
    "disidente",
    "restitucion",
    "tsunami",
    "fosa comun",
    "albergue",
    "protección",
    "lucha contra la corrupción",
    "puesto de policia",
    "excombatiente",
    "ocha",
    "colombia rural",
    "garantías",
    "ayuda internacional",
    "búsqueda de la paz",
    "mortal",
    "mutilacion",
    "perdón",
    "inaccesible",
    "dih",
    "grupos post desmovilizacion",
    "murio",
    "belico",
    "lideres sociales",
    "grupos pos desmovilizacion",
    "cultivos ilicitos",
    "diíalogos de paz",
    "programas de alimentación eficaces",
    "herid",
    "cultivos de uso ilícito",
    "temor",
    "abatido",
    "catastro actualizado",
    "catastro actualizado",
    "emergencia",
    "belica",
    "reclutamiento",
    "restitución",
    "crimen",
    "lluvias",
    "afectado",
    "construcción de vías terciarias",
    "fusil",
    "explosivo",
    "población rural",
    "atención y rehabilitación",
    "disparo",
    "desertor",
    "victima",
    "explosi",
    "mineria",
    "inclusión social del campo",
    "formalización de la propiedad",
    "desmembrado",
    "dijin",
    "intimid",
    "frente",
    "derrumbe",
    "desminado",
    "salud rural",
    "retaliacion",
    "banda criminal",
    "milita",
    "explotacion",
    "campo",
    "campo",
    "bloqu",
    "catastro",
    "mina antipersonal",
    "ultimar",
    "inclusión social",
    "remosion en masa",
    "decapitado",
    "restituci",
    "ultimado",
    "tiro",
    "accidente",
    "panfleto",
    "base militar",
    "confianza social",
    "bacrim",
    "explosion",
    "incautacion",
    "intimidada",
    "delincuencia",
    "narcotrafico",
    "autodefensas",
    "artefacto explosivo",
    "tortura",
    "capturado",
    "asesin",
    "intra-urbano",
    "protesta",
    "mutilación",
    "paz",
    "empleo rural",
    "esfuerzos de cooperación",
    "homicidio",
    "secues",
    "acciones de prevención",
    "gerard gomez",
    "farc",
    "huracan",
    "garantías de no repetición",
    "desnutricion",
    "trampa",
    "deslizamiento",
    "ilegal",
    "infanteria",
    "gerard gómez",
    "confinado",
    "bandas emergentes",
    "desminad",
    "medidas de reparación",
    "justicia",
    "venezolano",
    "snu",
    "planes nacionales rurales",
    "bacrin",
    "licito",
    "secuestro",
    "fuerza aerea",
    "apoyo al proceso de paz",
    "cuadrilla",
    "naciones unidas",
    "atención pscicosocial a víctimas",
    "onu",
    "restricción al acceso",
    "estímulo a la producción agropecuaria",
    "intimidado",
    "inversiones de la paz",
    "desertores",
    "financiación",
    "jurisdicción agraria",
    "ejercito",
    "desplazamiento forzado",
    "comando",
    "terrorista",
    "intimidación",
    "civil",
    "bala",
    "torrencial",
    "petardo",
    "sequia",
    "mata",
    "violación",
    "granada",
    "reparación a víctimas",
    "invierno",
    "policia",
    "confinar",
    "guarnicion",
    "conflicto",
    "conflicto",
    "campesinos colombianos",
    "proceso de paz",
    "proceso de paz",
    "oim",
    "comisión de la verdad",
    "afectada",
    "nuevos grupos armados",
    "reparación colectiva",
    "atención pscicosocial a victimas",
    "corrupción en colombia",
    "colombia",
    "volción",
    "bomba",
    "sismo",
    "oficina de envigado",
    "nuevos movimientos políticos",
    "impacto de bala",
    "sijin",
    "bloque",
    "armad",
    "clan del golfo",
    "verdad",
    "economía rural",
    "mina",
    "simulacro",
    "estacion",
    "reten ilegal",
    "organismos internacionales",
    "ministerio de agricultura y desarrollo rural",
    "esquirla",
    "perdidas",
    "baja en combate",
    "atracador",
    "prensa rural",
    "cooperación",
    "atentado",
    "desplazamiento",
    "rafaga",
    "mision medica",
    "retorno de comunidades",
    "los urabe",
    "matar",
    "emboscada",
    "respuesta humanitaria",
    "actos de reconocimiento de responsabilidad",
    "accion integral",
    "verano",
    "destruid",
    "paz con justicia social",
    "misión médica",
    "desaparicion forzada",
    "creciente",
    "incauta",
    "ataque a infraestructura",
    "arma",
    "pistola",
    "masacre",
    "homicid",
    "consolidacion",
    "batall",
    "sicariato",
    "guerrilla",
    "desactiv",
    "martin santiago",
    "riesgo",
    "liderezas",
    "riego y drenaje",
    "incursion",
    "campo minado",
    "incendio",
    "reclutamiento forzado",
    "auc",
    "confinamiento",
    "movilidad",
    "humanitario",
    "reparación",
    "asuntos humanitarios",
    "sector rural en colombia",
    "fumigacion de cultivos ilicitos",
    "epl"
  )

}
